# -*- coding: utf-8 -*-
r"""
make_web_data_v4.py —— v4 data packaging (copied from web\make_web_data.py, only changed input/output paths and pref seed)
================================================================================
Input: v4\\snn_trained_seed{seed}.json (export from train_snn_v4.py)
Output (default seed=20240521, --tag empty):
    v4\\snn_trained_v4.json   + v4\\snn_data_v4.js
Output (with --tag _seed20240522 etc.):
    v4\\snn_trained_v4{tag}.json + v4\\snn_data_v4{tag}.js

Differences from v3 web\\make_web_data.py:
  1) Never touches web\\snn_data.js / snn_trained.json (all outputs go to v4\\);
  2) pd_pref/wind_pref reconstruction seed taken from model meta.pref_seed (v3 fixed SEED=20240521;
     v4's make_pref varies with training seed, must use same seed to reconstruct, otherwise wind encoding is inconsistent).

Usage:
  py -3.13 v4\\make_web_data_v4.py --seed 20240521
  py -3.13 v4\\make_web_data_v4.py --seed 20240522 --tag _seed20240522
  py -3.13 v4\\make_web_data_v4.py --seed 20240521 --flip-dir   # Flip direction head (emergency, requires manual confirmation)
"""
import os
import sys
import json
import argparse

BASE = os.path.dirname(os.path.abspath(__file__))       # v4\
ROOT = os.path.dirname(BASE)
sys.path.insert(0, os.path.join(ROOT, 'pylibs'))        # Fallback: no need for external PYTHONPATH

import numpy as np


def make_pref(n_vis, n_wind, seed):
    rng = np.random.default_rng(seed)
    pd_pref = np.zeros((n_vis, 2), dtype=np.float32)
    pd_pref[:, 0] = np.linspace(-np.pi, np.pi, n_vis, endpoint=False)
    pd_pref[:, 1] = rng.uniform(0.5, 1.0, n_vis)  # Retained param (not connected to forward pass), keeps RNG order consistent with training side, do not delete
    wind_pref = rng.normal(size=(n_wind, 3)).astype(np.float32)
    wind_pref /= np.linalg.norm(wind_pref, axis=1, keepdims=True)
    return pd_pref, wind_pref


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--seed', type=int, default=20240521, help='Training seed (determines which snn_trained_seedXXX.json to read)')
    ap.add_argument('--tag', type=str, default='', help="Output filename suffix, e.g. _seed20240522; default '' -> snn_trained_v4.json / snn_data_v4.js")
    ap.add_argument('--flip-dir', action='store_true')
    args = ap.parse_args()

    model_path = os.path.join(BASE, f'snn_trained_seed{args.seed}.json')
    with open(model_path, encoding='utf-8') as f:
        data = json.load(f)

    n_vis = len(data['input_vision_indices'])
    n_wind = len(data['input_wind_indices'])
    pref_seed = int(data.get('meta', {}).get('pref_seed', 20240521))
    pd_pref, wind_pref = make_pref(n_vis, n_wind, pref_seed)
    data['pd_pref'] = [[round(float(a), 6), round(float(b), 6)] for a, b in pd_pref]
    data['wind_pref'] = [[round(float(x), 6) for x in r] for r in wind_pref]
    data['meta']['dir_flipped'] = bool(data['meta'].get('dir_flipped', False))  # Explicitly export direction flip flag

    if args.flip_dir:
        hd = data['head_dir']
        hd['w'] = [[-x for x in row] for row in hd['w']]
        hd['b'] = [-x for x in hd['b']]
        data['meta']['dir_flipped'] = True
        print('Direction readout head has been flipped (--flip-dir)')

    out_json = os.path.join(BASE, f'snn_trained_v4{args.tag}.json')
    with open(out_json, 'w', encoding='utf-8') as f:
        json.dump(data, f)

    out = os.path.join(BASE, f'snn_data_v4{args.tag}.js')
    with open(out, 'w', encoding='utf-8') as f:
        f.write('/* Generated by make_web_data_v4.py: trained SNN weights + sensor encoding params (v4) */\n')
        f.write('window.SNN_DATA = ')
        json.dump(data, f, separators=(',', ':'))
        f.write(';\n')
    print(f'Input {model_path} (train_seed={data["meta"].get("train_seed")} pref_seed={pref_seed})')
    print(f'Generated {out}  ({os.path.getsize(out) / 1e6:.2f} MB)')
    print(f'Generated {out_json}')
    print(f'Nodes {data["num_nodes"]} | Edges {len(data["edges"])} | vision input {n_vis} | wind input {n_wind}')


if __name__ == '__main__':
    main()
