# -*- coding: utf-8 -*-
"""
make_web_data.py — Generate web/snn_data.js (package trained model + sensor encoding parameters into JS loadable by web pages)
Also writes pd_pref / wind_pref back into snn_trained.json to ensure data consistency.
(pd_pref/wind_pref reproduced by make_pref(210, 325, SEED=20240521), identical to training pipeline)

Usage:
  python make_web_data.py              # Normal packaging
  python make_web_data.py --flip-dir   # Flip direction readout head (emergency fix for old models with inverted direction labels)
"""
import os
import sys
import json
import numpy as np

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SEED = 20240521


def make_pref(n_vis, n_wind, seed):
    rng = np.random.default_rng(seed)
    pd_pref = np.zeros((n_vis, 2), dtype=np.float32)
    pd_pref[:, 0] = np.linspace(-np.pi, np.pi, n_vis, endpoint=False)
    pd_pref[:, 1] = rng.uniform(0.5, 1.0, n_vis)  # Reserved parameter (not connected to forward pass), maintains RNG order consistency with training pipeline; do not delete
    wind_pref = rng.normal(size=(n_wind, 3)).astype(np.float32)
    wind_pref /= np.linalg.norm(wind_pref, axis=1, keepdims=True)
    return pd_pref, wind_pref


def main():
    model_path = os.path.join(BASE, 'snn_trained.json')
    with open(model_path, encoding='utf-8') as f:
        data = json.load(f)

    n_vis = len(data['input_vision_indices'])
    n_wind = len(data['input_wind_indices'])
    pd_pref, wind_pref = make_pref(n_vis, n_wind, SEED)
    data['pd_pref'] = [[round(float(a), 6), round(float(b), 6)] for a, b in pd_pref]
    data['wind_pref'] = [[round(float(x), 6) for x in r] for r in wind_pref]
    data['meta']['dir_flipped'] = bool(data['meta'].get('dir_flipped', False))  # Explicitly export direction flip marker

    if '--flip-dir' in sys.argv:
        hd = data['head_dir']
        hd['w'] = [[-x for x in row] for row in hd['w']]
        hd['b'] = [-x for x in hd['b']]
        data['meta']['dir_flipped'] = True
        print('Direction readout head flipped (--flip-dir)')

    with open(model_path, 'w', encoding='utf-8') as f:
        json.dump(data, f)

    out = os.path.join(BASE, 'web', 'snn_data.js')
    with open(out, 'w', encoding='utf-8') as f:
        f.write('/* Generated by make_web_data.py: trained SNN weights + sensor encoding parameters */\n')
        f.write('window.SNN_DATA = ')
        json.dump(data, f, separators=(',', ':'))
        f.write(';\n')
    print(f'Generated {out}  ({os.path.getsize(out) / 1e6:.2f} MB)')
    print(f'Nodes {data["num_nodes"]} | Edges {len(data["edges"])} | Vision input {n_vis} | Wind input {n_wind}')


if __name__ == '__main__':
    main()